src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

src/gallery/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^$', views.gallery_list, name='list'),
    url(r'^(?P<pk>[0-9]+)/$', views.gallery_detail, name='detail'),
    url(r'^create/$', views.gallery_create, name='create'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.gallery_update, name='edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.gallery_delete, name='delete'),

]

src/lisbon/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView
from . import views
from .sitemap import sitemaps

urlpatterns = [

    url(r'^$', views.home, name='home'),
    url(r'^robots\.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots_file"),
    url(r'^BingSiteAuth\.xml$', TemplateView.as_view(template_name="BingSiteAuth.xml", content_type="text/xml"), name="BingSiteAuth"),
    url(r'^googled15ef6cfc26e20bd\.html$', TemplateView.as_view(template_name="googled15ef6cfc26e20bd.html", content_type="text/html"), name="googled15ef6cfc26e20bd"),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^users/', include('profiles.urls', namespace='profiles')),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^tours/', include('tours.urls', namespace='tour')),
    url(r'^reviews/', include('review.urls', namespace='review')),
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    url(r'^contacts/', include('contacts.urls', namespace='contact')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^rent-car/', include('rent_car.urls', namespace='rent_car')),
    url(r'^rent-hotel/', include('rent_hotel.urls', namespace='rent_hotel')),
    url(r'^about/$', views.about, name='about'),
    url(r'^login-or-register/$', views.login_or_register, name='login_or_register'),
    url(r'^offers/', include('offer.urls', namespace='offer')),
    url(r'^category/', include('category.urls', namespace='category')),
    url(r'^related-links/', include('related_links.urls', namespace='related_links')),
    url(r'^booking/', include('booking.urls', namespace='booking')),
    url(r'^search/$', views.search, name='search'),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/news/urls.py
from django.conf.urls import url
from . import views

urlpatterns = (

    url(r'^$', views.news_list, name='list'),
    url(r'^create/$', views.news_create, name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.news_detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.news_update, name='edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.news_delete, name='delete'),
    # url(r'^(?P<slug>[\w-]+)/$', views.news_category, name='cat'),

)

src/offer/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.offer_list, name='list'),
    url(r'^create/$', views.offer_create, name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.offer_detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.offer_update, name='edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.offer_delete, name='delete'),
    url(r'^(?P<slug>[\w-]+)/$', views.offer_category, name='category'),

]

src/tours/urls.py
from django.conf.urls import url
from . import views

urlpatterns = (

    url(r'^$', views.tour_list, name='list'),
    url(r'^create/$', views.tour_create, name='create'),
    url(r'^success/$', views.tour_success, name='success'),
    url(r'^fail/$', views.tour_fail, name='fail'),
    url(r'^(?P<pk>[0-9]+)/$', views.tour_detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.tour_update, name='edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.tour_delete, name='delete'),
    url(r'^(?P<slug>[\w-]+)/$', views.tour_category, name='category'),

)

src/contacts/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = [

            'first_name',
            'first_name_preview',
            'last_name',
            'last_name_preview',
            'short_bio',
            'short_bio_preview',
            'img',
            'category',
            'category_preview',
            'mobile',
            'mobile_preview',
            'email',
            'email_preview',
            'whatsapp',
            'whatsapp_preview',
            'viber',
            'viber_preview',
            'telegram',
            'telegram_preview',
            'skype',
            'skype_preview',
            'facebook',
            'facebook_preview',
            'twitter',
            'twitter_preview',
            'pinterest',
            'pinterest_preview',
            'google',
            'google_preview',
            'instagram',
            'instagram_preview',
            'keywords_SEO',
            'description_SEO',
        ]

src/gallery/forms.py
from django import forms

from .models import Gallery


class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = [

            'title_PT',
            'title_EN',
            'title_DE',
            'description_PT',
            'description_EN',
            'description_DE',
            'img',
            'img_1',
            'img_2',
            'img_3',
            'img_4',
            'img_5',
            'video',
            'keywords_SEO',
            'description_SEO',

        ]

src/news/forms.py
from django import forms
from django.forms import DateTimeField

from .models import Article


class ArticleForm(forms.ModelForm):
    created_on = DateTimeField(widget=forms.widgets.DateTimeInput())

    class Meta:
        model = Article
        fields = '__all__'

src/offer/forms.py
from django import forms
from .models import Offer


class OfferForm(forms.ModelForm):
    class Meta:
        model = Offer
        fields = [

            'category',
            'tour_category',
            'title_PT',
            'title_EN',
            'title_DE',
            'position',
            'description_PT',
            'description_EN',
            'description_DE',
            'img',
            'keywords_SEO',
            'description_SEO',

        ]

src/related_links/forms.py
from django import forms

from .models import RelatedLink


class RelatedLinkForm(forms.ModelForm):
    class Meta:
        model = RelatedLink
        fields = [

            'title_PT',
            'title_EN',
            'title_DE',
            'description_PT',
            'description_EN',
            'description_DE',
            'link',
            'img',
            'html',
            'keywords_SEO',
            'description_SEO',

        ]

    def __init__(self, *args, **kwargs):
        super(RelatedLinkForm, self).__init__(*args, **kwargs)
        self.fields['img'].required = True

src/rent_car/forms.py
from django import forms
from .models import Car


class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = [

            'title_PT',
            'title_EN',
            'title_DE',
            'description_PT',
            'description_EN',
            'description_DE',
            'category',
            'price',
            'img',
            'keywords_SEO',
            'description_SEO',

        ]

src/tours/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from lisbon.forms import contains_html_tags, contains_url
from .models import Tour


class TourForm(forms.ModelForm):
    class Meta:
        model = Tour
        fields = [

            'category',
            'position',
            'title_PT',
            'title_EN',
            'title_DE',
            'description_PT',
            'description_EN',
            'description_DE',
            'short_description_PT',
            'short_description_EN',
            'short_description_DE',
            'price',
            'img',
            'url',
            'keywords_SEO',
            'description_SEO',

        ]


class BookNow(forms.Form):
    fullname = forms.CharField(label=_('Name'), required=True, validators=[contains_html_tags, contains_url])
    email = forms.EmailField(label=_('Email'), required=True, validators=[contains_html_tags, contains_url])
    phone = forms.CharField(label=_('Phone'), required=True, validators=[contains_html_tags, contains_url])
    message = forms.CharField(label=_('Message'), widget=forms.Textarea(), required=True,
                              validators=[contains_html_tags, contains_url])
    date = forms.DateField(label=_('From Date'), required=True)


class ContactMe(forms.Form):
    fullname = forms.CharField(label=_('Name'), required=True, validators=[contains_html_tags, contains_url])
    email = forms.EmailField(label=_('Email'), required=True, validators=[contains_html_tags, contains_url])
    phone = forms.CharField(label=_('Phone'), required=True, validators=[contains_html_tags, contains_url])
    message = forms.CharField(label=_('Message'), widget=forms.Textarea(), required=True,
                              validators=[contains_html_tags, contains_url])

src/contacts/views.py
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import ugettext_lazy as _

from helpers.models import Helpers
from offer.models import OfferCategory
from tours.models import Category
from .forms import ContactForm
from .models import Contact, ContactHelpers


def get_lang(request):
    lang = request.LANGUAGE_CODE
    return lang


def get_company():
    return Helpers.objects.get(id=1).company_name


def contact_list(request):
    lang = get_lang(request)
    queryset_list = Contact.objects.all()
    breadcrumbs = [
        {'url': '/', 'name': _('Home')},
        {'url': '#', 'name': _('Contacts'), 'active': True}
    ]
    query = request.GET.get('q')
    if query:
        return redirect(reverse('search') + '?q=' + query)
    paginator = Paginator(queryset_list, ContactHelpers.objects.get(id=1).pagination)
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    footer = {
        'pt': Helpers.objects.get(id=1).about_footer_PT,
        'en': Helpers.objects.get(id=1).about_footer_EN,
        'de': Helpers.objects.get(id=1).about_footer_DE
    }
    context = {
        'footer': {
            'about': footer[lang],
            'icon': Helpers.objects.get(id=1).footer_icon
        },
        'nav': {
            'tour_categories_list': Category.objects.all(),
            'offer_categories_list': OfferCategory.objects.all(),
        },
        'company': get_company(),
        'title': _('Contacts'),
        'breadcrumbs': breadcrumbs,
        'object_list': queryset,
        'page_request_var': page_request_var,
    }

    return render(request, 'partials/contact.html', context)


def contact_detail(request, pk=None):
    lang = get_lang(request)
    contact = Contact.objects.get(pk=pk)
    query = request.GET.get('q')
    if query:
        return redirect(reverse('search') + '?q=' + query)
    breadcrumbs = [
        {'url': '/', 'name': _('Home')},
        {'url': '/contacts', 'name': _('Contacts')},
        {'url': '#', 'name': contact.first_name + ' ' + contact.last_name, 'active': True}
    ]
    footer = {
        'pt': Helpers.objects.get(id=1).about_footer_PT,
        'en': Helpers.objects.get(id=1).about_footer_EN,
        'de': Helpers.objects.get(id=1).about_footer_DE
    }
    context = {
        'footer': {
            'about': footer[lang],
            'icon': Helpers.objects.get(id=1).footer_icon
        },
        'nav': {
            'tour_categories_list': Category.objects.all(),
            'offer_categories_list': OfferCategory.objects.all(),
        },
        'company': get_company(),
        'title': contact.first_name + ' ' + contact.last_name,
        'breadcrumbs': breadcrumbs,
        'object': contact,
    }

    return render(request, 'templates/_contact_details.html', context)


def contact_create(request):
    query = request.GET.get('q')
    if query:
        return redirect(reverse('search') + '?q=' + query)
    lang = get_lang(request)
    footer = {
        'pt': Helpers.objects.get(id=1).about_footer_PT,
        'en': Helpers.objects.get(id=1).about_footer_EN,
        'de': Helpers.objects.get(id=1).about_footer_DE
    }
    if not request.user.is_staff or not request.user.is_superuser:
        return redirect('accounts:signup')
    else:
        form = ContactForm(request.POST or None, request.FILES or None)
        breadcrumbs = [
            {'url': '/', 'name': _('Home')},
            {'url': '/contacts', 'name': _('Contacts')},
            {'url': '#', 'name': _('Create Contact'), 'active': True}
        ]
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            messages.success(request, _('Contact Created'))
            return redirect('contact:list')

        context = {

            'footer': {
                'about': footer[lang],
                'icon': Helpers.objects.get(id=1).footer_icon
            },
            'nav': {
                'tour_categories_list': Category.objects.all(),
                'offer_categories_list': OfferCategory.objects.all(),
            },
            'company': get_company(),
            'title': _('Create Contact'),
            'breadcrumbs': breadcrumbs,
            'value': _('Add'),
            'form': form
        }

        return render(request, 'templates/_form.html', context)


def contact_update(request, pk=None):
    query = request.GET.get('q')
    if query:
        return redirect(reverse('search') + '?q=' + query)
    lang = get_lang(request)
    footer = {
        'pt': Helpers.objects.get(id=1).about_footer_PT,
        'en': Helpers.objects.get(id=1).about_footer_EN,
        'de': Helpers.objects.get(id=1).about_footer_DE
    }
    if not request.user.is_staff or not request.user.is_superuser:
        return redirect('accounts:signup')
    else:
        contact = get_object_or_404(Contact, pk=pk)
        breadcrumbs = [
            {'url': '/', 'name': _('Home')},
            {'url': '/contacts', 'name': _('Contacts')},
            {'url': '#', 'name': contact.first_name + ' ' + contact.last_name, 'active': True}
        ]
        form = ContactForm(request.POST or None, request.FILES or None, instance=contact)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.save()
            messages.success(request, _('Contact saved'))
            return redirect('contact:list')

        context = {
            'footer': {
                'about': footer[lang],
                'icon': Helpers.objects.get(id=1).footer_icon
            },
            'nav': {
                'tour_categories_list': Category.objects.all(),
                'offer_categories_list': OfferCategory.objects.all(),
            },
            'company': get_company(),
            'title': _('Contact Edit'),
            'breadcrumbs': breadcrumbs,
            'instance': contact,
            'form': form,
            'value': _('Add'),
        }
        return render(request, 'templates/_form.html', context)


def contact_delete(request, pk=None):
    if not request.user.is_staff or not request.user.is_superuser:
        return redirect('accounts:signup')
    instance = get_object_or_404(Contact, pk=pk)
    instance.delete()
    messages.success(request, _('Contact deleted'))
    return redirect('contact:list')

src/templates/partials/contact.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{{ title }}{% endblock title %}
{% block beadcrumbs %}
    {% include 'templates/_breadcrumbs.html' %}
{% endblock %}
{% block content %}
    <section>
    <div class="container contact">
        <h1 class="display-4">{{ title }}</h1>
        <div class="row">
            {% for object in object_list %}
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                    {% include 'templates/_contact_card.html' %}
                </div>
            {% endfor %}
        </div>
        {% if user.is_staff or user.is_superuser %}
            <a class="btn btn-warning" href="{% url 'contact:create' %}">
                <i class="fa fa-plus"></i>
                {% trans 'Create Contact' %}
            </a>
        {% endif %}
        {% include 'templates/_pagination.html' %}
    </div>
    </section>
{% endblock %}

src/templates/partials/gallery.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
    {% include 'templates/_breadcrumbs.html' %}
    <section>
        <div class="container">
            <h1 class="display-4">{{ title }}</h1>
            <div class="card-columns">
                {% for object in object_list %}
                    {% include 'templates/_gallery_card.html' %}
                {% endfor %}
            </div>
            {% if user.is_staff or user.is_superuser %}
                <a class="btn btn-warning" href="{% url 'gallery:create' %}"><i class="fa fa-plus"></i> {% trans 'Create Gallery' %}</a>
            {% endif %}
            {% include 'templates/_pagination.html' %}
        </div>
    </section>
{% endblock %}

src/templates/partials/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load thumbnail %}
{% load crispy_forms_tags %}
{% block title %}Excursions Lisbon - Day Tours in Lisbon and Portugal with Professional Guide{% endblock %}
{% block keywords %}Excursions Lisbon,Excursions to Lisbon,Excursions in Lisbon,Tours in lisbon,Lisbon
    Excursions{% endblock keywords %}
{% block description %}Excursions Lisbon - Day Tours in Lisbon and Portugal with Professional Guide.xcursions Lisbon
    will organize for you in Lisbon : Walking City Tours, Tours to Sintra, Guided Tours in Portugal, Group Tours in
    Lisbon, Fishing Tours and Transfers.{% endblock description %}
{% block content %}
    <img style="display: none;" src="{% static 'img/lisbon_tram.jpg' %}" alt="Excursions Lisbon">
    {% include 'templates/_breadcrumbs.html' %}
    <article class="tours-header offer">
        <div class="container">
            <div class="col-xs-12 col-sm-12 col-md-6" style="text-align: center">
                <a target="_blank" href="https://www.visitportugal.com/en/content/clean-and-safe">
                    <img style="width: 50%;" src="{% static '/media/certificate_clean_and_safe.jpg' %}"
                         alt="Clean and Safe">
                </a>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-6" style="padding-top: 100px;">
                {% if 'pt' in request.LANGUAGE_CODE %}
                    Nossa empresa recebeu o certificado <a target="_blank" href="https://www.visitportugal.com/en/content/clean-and-safe"><em>Clean and Safe</em></a> que garante que os nossos clientes podem ficar em
                    segurança connosco!
                {% endif %}
                {% if 'en' in request.LANGUAGE_CODE %}
                    We have received the official certificate <a target="_blank" href="https://www.visitportugal.com/en/content/clean-and-safe"><em>Clean and Safe</em></a> from Turismo de Portugal which means that all
                    our clients will be safe to travel with us!
                {% endif %}
                {% if 'de' in request.LANGUAGE_CODE %}
                    Wir haben das offizielle Zertifikat <a target="_blank" href="https://www.visitportugal.com/en/content/clean-and-safe"><em>Clean and Safe</em></a> von Turismo de Portugal erhalten, was bedeutet,
                    dass alle unsere Kunden sicher mit uns reisen können!
                {% endif %}
            </div>
        </div>
    </article>
    <article class="offer">
        <div class="container">
            <div class="col-xs-12 col-sm-12 col-md-6">
                <a href="http://excursions-lisbon.com/">
                    <img style="width: 100%;" src="{% static 'img/lisbon_tram.jpg' %}" alt="Excursions Lisbon">
                </a>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-6">
                <h1 style="text-align: center;">Excursions Lisbon</h1>
                <p>
                    <strong>
                        <a href="http://excursions-lisbon.com/">Excursions Lisbon</a>
                    </strong> – day Tours in Lisbon and Portugal with Professional Guide. Excursions Lisbon will
                    organize for you in Lisbon: Walking Lisbon Tours, Tours to Sintra, Day Tours Lisbon, Guided Tours in
                    Portugal, Group Tours in Lisbon, Fishing Tours and Transfers.
                </p>
                <p>
                    <strong>
                        <a href="http://excursions-lisbon.com/">Excursions Lisbon</a>
                    </strong> – hello there dear visitors of Lisbon, my name is Marian Danici and I am professional
                    interpreter-guide and also CEO of my family travel firm. With us you can book unforgettable
                    excursions in
                    Lisbon, transfers from/to Lisbon airport, interesting walking tours in Lisbon city, the most tasty
                    gastronomic tours, unbelievable sea trips, big game fishing trips, guided private tours, guided
                    group tours
                    in Lisbon and Portugal and many more. Our staff including me will show you every monument they know
                    and
                    share with you the knowledge about history of Lisbon and Portugal. Our guides speak English, Spanish
                    and
                    Portuguese. Should you need any other language please let us know.
                </p>
                <p>
                    <em>
                        <strong>Lisbon is a great capital of Portugal</strong>
                    </em> and it has one of the biggest ports in the country. It has a great and rich history which can
                    be seen
                    through its majestic architectural monuments. Lisbon city is one of the oldest cities in Western
                    Europe and
                    it attracts a lot of tourists with its unique Mediterranean climate and a huge offer of
                    entertainments of
                    different levels
                </p>
            </div>
        </div>
    </article>
    <article class="tours">
        <div class="container">
            <h3 class="display-3 text-md-center">{{ section.tour_header }}</h3>
            <p style="text-align: center">
                <a href="{% url 'tour:list' %}"><em>{% trans 'full tour list' %}</em></a>
            </p>
            <div style="display: flex; align-items: flex-start; justify-content: space-around; flex-wrap: wrap;">

                {% if 'pt' in request.LANGUAGE_CODE %}
                    {% for object in tour_list %}
                        {% include 'templates/_tour_card_pt.html' %}
                    {% endfor %}
                {% endif %}
                {% if 'en' in request.LANGUAGE_CODE %}
                    {% for object in tour_list %}
                        {% include 'templates/_tour_card_gb.html' %}
                    {% endfor %}
                {% endif %}
                {% if 'de' in request.LANGUAGE_CODE %}
                    {% for object in tour_list %}
                        {% include 'templates/_tour_card_de.html' %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        {% if user.is_staff or user.is_superuser %}
            <a class="btn btn-warning" href="{% url 'tour:create' %}">
                <i class="fa fa-plus"></i> {% trans 'Create Tour' %}</a>
        {% endif %}
        {% include 'templates/_pagination.html' %}
        </div>
    </article>
    <article class="tours">
        <div class="container">
            <div class="col-xs-12 col-sm-12 col-md-6">
                <a href="http://excursions-lisbon.com/">
                    <img style="width: 100%;" src="{% static 'img/Excursions-Lisbon.jpg' %}" alt="Excursions Lisbon">
                </a>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-6">
                <h2 style="text-align: center;"><a href="http://excursions-lisbon.com/">Excursions in Lisbon</a></h2>
                <p>Our
                    <a href="http://excursions-lisbon.com/">
                        <span style="text-decoration: underline;">Excursions in Lisbon</span>
                    </a>
                    are full of varieties and different amazing routes which will make you see Lisbon with the eyes of
                    the
                    local people. Our interpreter-guides are local and all qualified professionals, friendly persons and
                    they love working with Lisbon visitors. Our favorite monument in Lisbon is Monsteiro dos Jeronimos.
                    It is outstanding architectural monument which attracts a lot of tourists every year. It took nearly
                    a
                    hundred years to build that great monument and it has pure Portuguese architectural style which is
                    called
                    Manuelinho. Also that monument is a kind of national Renaissance and it has got elements of Gothic
                    and
                    Moorish styles. That Monestary was a shelter for a long time for Jerome monks who served very well
                    to
                    the king Manuel I. It has been many years when the Monestary was dissolved and became a national
                    property
                    of Portugal. Now it is a Archaeological Museum which you can visit with our help.
                </p>
            </div>
        </div>
    </article>

    <article class="offer">
        <div class="container">
            <h3 style="text-align: center;"><a href="http://excursions-lisbon.com/">Tours and excursions in Lisbon</a>
            </h3>
            <p>Booking our <em><a href="http://excursions-lisbon.com/">tours and excursions in Lisbon</a></em> you
                receive quality and sympathy. We have to offer a lot of interesting tours and amazing excursions in
                Lisbon and Portugal. We are professionals and we love what you do. You will be very welcome in Lisbon
                and it would be very nice to meet you!</p>
        </div>
    </article>
    {% include 'templates/_offers_home.html' %}

    <article class="carousel">
        <div class="container">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="4"></li>
                </ol>
                <div style="min-height: 600px; max-height: 600px" class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img style="width: 100%;object-fit: cover; min-height: 600px"
                             src="{% thumbnail img1 1920x1080 crop="smart" %}" alt="{{ header }}">
                        <p class="main-header display-3 type">{{ header }}</p>
                    </div>
                    <div class="carousel-item">
                        <img style="width: 100%;object-fit: cover; min-height: 600px"
                             src="{% thumbnail img2 1920x1080 crop="smart" %}" alt="{{ header }}">
                        <p class="main-header display-3 type">{{ header }}</p>
                    </div>
                    <div class="carousel-item">
                        <img style="width: 100%;object-fit: cover; min-height: 600px"
                             src="{% thumbnail img3 1920x1080 crop="smart" %}" alt="{{ header }}">
                        <p class="main-header display-3 type">{{ header }}</p>
                    </div>
                    <div class="carousel-item">
                        <img style="width: 100%;object-fit: cover; min-height: 600px"
                             src="{% thumbnail img4 1920x1080 crop="smart" %}" alt="{{ header }}">
                        <p class="main-header display-3 type">{{ header }}</p>
                    </div>
                    <div class="carousel-item">
                        <img style="width: 100%;object-fit: cover; min-height: 600px"
                             src="{% thumbnail img5 1920x1080 crop="smart" %}" alt="{{ header }}">
                        <p class="main-header display-3 type">{{ header }}</p>
                    </div>
                </div>
                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                    <span class="icon-prev" aria-hidden="true"></span>
                    <span class="sr-only">{% trans 'Previous' %}</span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                    <span class="icon-next" aria-hidden="true"></span>
                    <span class="sr-only">{% trans 'Next' %}</span>
                </a>
            </div>
        </div>
    </article>

    {% include 'templates/modal/_delete_tour.html' %}
    {% include 'templates/_modal_book_now.html' %}
{% endblock content %}

src/templates/partials/login_or_register.html
{% extends 'base.html' %}
{% block beadcrumbs %}
    {% include 'templates/_breadcrumbs.html' %}
{% endblock %}
{% block content %}
    <section>
    <div class="container">
        <h3 class="display-4">Please LOGIN or REGISTER to leave your reviews or comments. Thank you!</h3>
        <a class="btn btn-lg btn-success" href="{% url 'accounts:login' %}">Login</a>
        <a class="btn btn-lg btn-success" href="{% url 'accounts:signup' %}">Register</a>
    </div>
    </section>
{% endblock %}