src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

src/lisbon/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView
from . import views
from .sitemap import sitemaps

urlpatterns = [

    url(r'^$', views.home, name='home'),
    url(r'^robots\.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots_file"),
    url(r'^BingSiteAuth\.xml$', TemplateView.as_view(template_name="BingSiteAuth.xml", content_type="text/xml"), name="BingSiteAuth"),
    url(r'^googled15ef6cfc26e20bd\.html$', TemplateView.as_view(template_name="googled15ef6cfc26e20bd.html", content_type="text/html"), name="googled15ef6cfc26e20bd"),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^users/', include('profiles.urls', namespace='profiles')),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^tours/', include('tours.urls', namespace='tour')),
    url(r'^reviews/', include('review.urls', namespace='review')),
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    url(r'^contacts/', include('contacts.urls', namespace='contact')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^rent-car/', include('rent_car.urls', namespace='rent_car')),
    url(r'^rent-hotel/', include('rent_hotel.urls', namespace='rent_hotel')),
    url(r'^about/$', views.about, name='about'),
    url(r'^login-or-register/$', views.login_or_register, name='login_or_register'),
    url(r'^offers/', include('offer.urls', namespace='offer')),
    url(r'^category/', include('category.urls', namespace='category')),
    url(r'^related-links/', include('related_links.urls', namespace='related_links')),
    url(r'^booking/', include('booking.urls', namespace='booking')),
    url(r'^search/$', views.search, name='search'),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/news/urls.py
from django.conf.urls import url
from . import views

urlpatterns = (

    url(r'^$', views.news_list, name='list'),
    url(r'^create/$', views.news_create, name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.news_detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.news_update, name='edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.news_delete, name='delete'),
    # url(r'^(?P<slug>[\w-]+)/$', views.news_category, name='cat'),

)

src/accounts/forms.py
from __future__ import unicode_literals
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from authtools import forms as authtoolsforms
from django.contrib.auth import forms as authforms
from django.core.urlresolvers import reverse


class LoginForm(AuthenticationForm):
    remember_me = forms.BooleanField(required=False, initial=False)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields["username"].widget.input_type = "email"  # ugly hack

        self.helper.layout = Layout(
            Field('username', placeholder="Enter Email", autofocus=""),
            Field('password', placeholder="Enter Password"),
            HTML('<a href="{}">Forgot Password?</a>'.format(
                reverse("accounts:password-reset"))),
            Field('remember_me'),
            Submit('sign_in', 'Log in',
                   css_class="btn btn-lg btn-primary btn-block"),
            )


class SignupForm(authtoolsforms.UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields["email"].widget.input_type = "email"  # ugly hack

        self.helper.layout = Layout(
            Field('email', placeholder="Enter Email", autofocus=""),
            Field('name', placeholder="Enter Full Name"),
            Field('password1', placeholder="Enter Password"),
            Field('password2', placeholder="Re-enter Password"),
            Submit('sign_up', 'Sign up', css_class="btn-warning"),
            )


class PasswordChangeForm(authforms.PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.layout = Layout(
            Field('old_password', placeholder="Enter old password",
                  autofocus=""),
            Field('new_password1', placeholder="Enter new password"),
            Field('new_password2', placeholder="Enter new password (again)"),
            Submit('pass_change', 'Change Password', css_class="btn-warning"),
            )


class PasswordResetForm(authtoolsforms.FriendlyPasswordResetForm):

    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.layout = Layout(
            Field('email', placeholder="Enter email",
                  autofocus=""),
            Submit('pass_reset', 'Reset Password', css_class="btn-warning"),
            )


class SetPasswordForm(authforms.SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(SetPasswordForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.layout = Layout(
            Field('new_password1', placeholder="Enter new password",
                  autofocus=""),
            Field('new_password2', placeholder="Enter new password (again)"),
            Submit('pass_change', 'Change Password', css_class="btn-warning"),
            )

src/tours/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from lisbon.forms import contains_html_tags, contains_url
from .models import Tour


class TourForm(forms.ModelForm):
    class Meta:
        model = Tour
        fields = [

            'category',
            'position',
            'title_PT',
            'title_EN',
            'title_DE',
            'description_PT',
            'description_EN',
            'description_DE',
            'short_description_PT',
            'short_description_EN',
            'short_description_DE',
            'price',
            'img',
            'url',
            'keywords_SEO',
            'description_SEO',

        ]


class BookNow(forms.Form):
    fullname = forms.CharField(label=_('Name'), required=True, validators=[contains_html_tags, contains_url])
    email = forms.EmailField(label=_('Email'), required=True, validators=[contains_html_tags, contains_url])
    phone = forms.CharField(label=_('Phone'), required=True, validators=[contains_html_tags, contains_url])
    message = forms.CharField(label=_('Message'), widget=forms.Textarea(), required=True,
                              validators=[contains_html_tags, contains_url])
    date = forms.DateField(label=_('From Date'), required=True)


class ContactMe(forms.Form):
    fullname = forms.CharField(label=_('Name'), required=True, validators=[contains_html_tags, contains_url])
    email = forms.EmailField(label=_('Email'), required=True, validators=[contains_html_tags, contains_url])
    phone = forms.CharField(label=_('Phone'), required=True, validators=[contains_html_tags, contains_url])
    message = forms.CharField(label=_('Message'), widget=forms.Textarea(), required=True,
                              validators=[contains_html_tags, contains_url])

src/accounts/views.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.contrib.auth import get_user_model
from django.contrib import auth
from django.contrib import messages
from authtools import views as authviews
from braces import views as bracesviews
from django.conf import settings
from . import forms

User = get_user_model()


class LoginView(bracesviews.AnonymousRequiredMixin,
                authviews.LoginView):
    template_name = "accounts/login.html"
    form_class = forms.LoginForm

    def form_valid(self, form):
        redirect = super(LoginView, self).form_valid(form)
        remember_me = form.cleaned_data.get('remember_me')
        if remember_me is True:
            ONE_MONTH = 30 * 24 * 60 * 60
            expiry = getattr(settings, "KEEP_LOGGED_DURATION", ONE_MONTH)
            self.request.session.set_expiry(expiry)
        return redirect


class LogoutView(authviews.LogoutView):
    url = reverse_lazy('home')


class SignUpView(bracesviews.AnonymousRequiredMixin,
                 bracesviews.FormValidMessageMixin,
                 generic.CreateView):
    form_class = forms.SignupForm
    model = User
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('home')
    form_valid_message = "You're signed up!"

    def form_valid(self, form):
        r = super(SignUpView, self).form_valid(form)
        username = form.cleaned_data["email"]
        password = form.cleaned_data["password1"]
        user = auth.authenticate(email=username, password=password)
        auth.login(self.request, user)
        return r


class PasswordChangeView(authviews.PasswordChangeView):
    form_class = forms.PasswordChangeForm
    template_name = 'accounts/password-change.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.save()
        messages.success(self.request,
                         "Your password was changed, "
                         "hence you have been logged out. Please relogin")
        return super(PasswordChangeView, self).form_valid(form)


class PasswordResetView(authviews.PasswordResetView):
    form_class = forms.PasswordResetForm
    template_name = 'accounts/password-reset.html'
    success_url = reverse_lazy('accounts:password-reset-done')
    subject_template_name = 'accounts/emails/password-reset-subject.txt'
    email_template_name = 'accounts/emails/password-reset-email.html'


class PasswordResetDoneView(authviews.PasswordResetDoneView):
    template_name = 'accounts/password-reset-done.html'


class PasswordResetConfirmView(authviews.PasswordResetConfirmAndLoginView):
    template_name = 'accounts/password-reset-confirm.html'
    form_class = forms.SetPasswordForm

src/accounts/templates/accounts/auth_base.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <section>
    <div class="container form-box">
        <div class="text-center">
            <h2>{% block form_heading %}{% endblock %}</h2>
        </div>
        {% block form %}
        {% endblock %}
    </div>
    </section>
{% endblock %}

src/accounts/templates/accounts/login.html
{% extends 'accounts/auth_base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ block.super }}Log In{% endblock %}
{% block form_heading %}Please Log In{% endblock %}
{% block form %}
    <style>
        .form-signin {
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
        }

        .form-signin .form-signin-heading,
        .form-signin .checkbox {
            margin-bottom: 10px;
        }

        .form-signin .checkbox {
            font-weight: normal;
        }

        .form-signin .form-group {
            margin-bottom: 0;
        }

        .form-signin .form-control {
            position: relative;
            height: auto;
            -webkit-box-sizing: border-box;
            box-sizing: border-box;
            padding: 10px;
            font-size: 16px;
        }

        .form-signin .form-control:focus {
            z-index: 2;
        }

        .form-signin label {
            display: none;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>
    <div class="form-signin">
        <form method="post" action="{{ request.get_full_path }}?next=/">
            {% csrf_token %}
            <div id="div_id_username" class="form-group">
                <label for="id_username" class="control-label requiredField">
                    Email address<span class="asteriskField">*</span>
                </label>
                <div class="controls">
                    <input autofocus="" class="textinput textInput form-control" id="id_username" maxlength="254"
                           name="username" placeholder="Enter Email" type="email"/></div>
            </div>
            <div id="div_id_password" class="form-group"><label for="id_password" class="control-label  requiredField">
                Password<span class="asteriskField">*</span> </label>
                <div class="controls "><input class="textinput textInput form-control" id="id_password" name="password"
                                              placeholder="Enter Password" type="password"/></div>
            </div>
            <a href="/password-reset/">Forgot Password?</a>
            <div class="form-group">
                <div id="div_id_remember_me" class="checkbox"><label for="id_remember_me" class=""> <input
                        class="checkboxinput" id="id_remember_me" name="remember_me" type="checkbox"/>
                    Remember me
                </label></div>
            </div>
            <input type="submit"
                   name="sign_in"
                   value="Log in"

                   class="btn btn-primary btn btn-lg btn-primary btn-block"
                   id="submit-id-sign_in"/>
        </form>
        <p>Don't have an account? <a href="{% url 'accounts:signup' %}">Sign up</a>.</p>
    </div>
    <div class="form-message">

    </div>
    <script>
        $('h2').each(function () {
            $(this).css('text-align', 'center')

        })
    </script>
{% endblock form %}

src/accounts/templates/accounts/password-change.html
{% extends 'accounts/auth_base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ block.super }}Password Change{% endblock %}
{% block form_heading %}Password Change{% endblock %}
{% block form %}
    <form method="post" action="{{ request.get_full_path }}">
        {% csrf_token %}
        <div id="div_id_old_password" class="form-group">
            <label for="id_old_password" class="control-label  requiredField">
                Old password<span class="asteriskField">*</span> </label>
            <div class="controls"><input autofocus="" class="textinput textInput form-control" id="id_old_password"
                                          name="old_password" placeholder="Enter old password" type="password"/></div>
        </div>
        <div id="div_id_new_password1" class="form-group">
            <label for="id_new_password1" class="control-label  requiredField">
                New password<span class="asteriskField">*</span> </label>
            <div class="controls "><input class="textinput textInput form-control" id="id_new_password1"
                                          name="new_password1" placeholder="Enter new password" type="password"/></div>
        </div>
        <div id="div_id_new_password2" class="form-group">
            <label for="id_new_password2" class="control-label  requiredField">
                New password confirmation<span class="asteriskField">*</span> </label>
            <div class="controls "><input class="textinput textInput form-control" id="id_new_password2"
                                          name="new_password2" placeholder="Enter new password (again)"
                                          type="password"/></div>
        </div>
        <input type="submit"
               name="pass_change"
               value="Change Password"
               class="btn btn-primary btn-warning"
               id="submit-id-pass_change"/>
    </form>
{% endblock form %}

src/accounts/templates/accounts/password-reset-confirm.html
{% extends 'accounts/auth_base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ block.super }}Password Change{% endblock %}
{% block form_heading %}Password Change{% endblock %}
{% block form %}
    <form method="post" action="{{ request.get_full_path }}">
        {% csrf_token %}
        <div id="div_id_new_password1" class="form-group">
            <label for="id_new_password1" class="control-label  requiredField">
                New password<span class="asteriskField">*</span>
            </label>
            <div class="controls">
                <input autofocus="" class="textinput textInput form-control" id="id_new_password1" name="new_password1"
                       placeholder="Enter new password" type="password"/>
            </div>
        </div>
        <div id="div_id_new_password2" class="form-group">
            <label for="id_new_password2" class="control-label  requiredField">
                New password confirmation<span class="asteriskField">*</span>
            </label>
            <div class="controls">
                <input class="textinput textInput form-control" id="id_new_password2" name="new_password2"
                       placeholder="Enter new password (again)" type="password"/>
            </div>
        </div>
        <input type="submit"
               name="pass_change"
               value="Change Password"
               class="btn btn-primary btn-warning"
               id="submit-id-pass_change"/>
    </form>
{% endblock form %}

src/accounts/templates/accounts/password-reset-done.html
{% extends 'accounts/auth_base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ block.super }}Password Reset Done{% endblock %}
{% block form_heading %}Password Reset Email Sent{% endblock %}
{% block form %}
    <div class="form-message">
        <p>
            Please check your mail. You would have received a password reset mail from us.
        </p>
    </div>
{% endblock form %}

src/accounts/templates/accounts/password-reset.html
{% extends 'accounts/auth_base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ block.super }}Password Reset{% endblock %}
{% block form_heading %}Password Reset{% endblock %}
{% block form %}
    <form method="post" action="{{ request.get_full_path }}">
        {% csrf_token %}
        <div id="div_id_email" class="form-group">
            <label for="id_email" class="control-label  requiredField">
                Email<span class="asteriskField">*</span>
            </label>
            <div class="controls ">
                <input autofocus="" class="emailinput form-control" id="id_email" maxlength="254"
                       name="email" placeholder="Enter email" type="email"/></div>
        </div>
        <input type="submit"
               name="pass_reset"
               value="Reset Password"
               class="btn btn-primary btn-warning"
               id="submit-id-pass_reset"/>
    </form>
{% endblock form %}

src/accounts/templates/accounts/signup.html
{% extends 'accounts/auth_base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ block.super }}Sign Up{% endblock %}
{% block form_heading %}Signing Up is Free{% endblock %}
{% block form %}
    <form method="post" action="{{ request.get_full_path }}?next=/">
        {% csrf_token %}
        <div id="div_id_email" class="form-group"><label for="id_email" class="control-label  requiredField">
            Email address<span class="asteriskField">*</span> </label>
            <div class="controls"><input autofocus="" class="emailinput form-control" id="id_email" maxlength="255"
                                          name="email" placeholder="Enter Email" type="email"/></div>
        </div>
        <div id="div_id_name" class="form-group"><label for="id_name" class="control-label  requiredField">
            Name<span class="asteriskField">*</span> </label>
            <div class="controls"><input class="textinput textInput form-control" id="id_name" maxlength="255"
                                          name="name" placeholder="Enter Full Name" type="text"/></div>
        </div>
        <div id="div_id_password1" class="form-group"><label for="id_password1" class="control-label  requiredField">
            Password<span class="asteriskField">*</span> </label>
            <div class="controls"><input class="textinput textInput form-control" id="id_password1" name="password1"
                                          placeholder="Enter Password" type="password"/></div>
        </div>
        <div id="div_id_password2" class="form-group"><label for="id_password2" class="control-label  requiredField">
            Password confirmation<span class="asteriskField">*</span> </label>
            <div class="controls"><input class="textinput textInput form-control" id="id_password2" name="password2"
                                          placeholder="Re-enter Password" type="password"/>
                <p id="hint_id_password2" class="help-block">Enter the same password as above, for verification.</p>
            </div>
        </div>
        <input type="submit"
               name="sign_up"
               value="Sign up"

               class="btn btn-primary btn-warning"
               id="submit-id-sign_up"/>
    </form>
    <div class="form-message">
        <p>Already signed up? <a href="{% url 'accounts:login' %}">Log in</a>.</p>
    </div>
{% endblock form %}