src/lisbon/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView
from . import views
from .sitemap import sitemaps

urlpatterns = [

    url(r'^$', views.home, name='home'),
    url(r'^robots\.txt$', TemplateView.as_view(template_name="robots.txt", content_type="text/plain"), name="robots_file"),
    url(r'^BingSiteAuth\.xml$', TemplateView.as_view(template_name="BingSiteAuth.xml", content_type="text/xml"), name="BingSiteAuth"),
    url(r'^googled15ef6cfc26e20bd\.html$', TemplateView.as_view(template_name="googled15ef6cfc26e20bd.html", content_type="text/html"), name="googled15ef6cfc26e20bd"),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^', include('accounts.urls', namespace='accounts')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^users/', include('profiles.urls', namespace='profiles')),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^tours/', include('tours.urls', namespace='tour')),
    url(r'^reviews/', include('review.urls', namespace='review')),
    url(r'^gallery/', include('gallery.urls', namespace='gallery')),
    url(r'^contacts/', include('contacts.urls', namespace='contact')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^rent-car/', include('rent_car.urls', namespace='rent_car')),
    url(r'^rent-hotel/', include('rent_hotel.urls', namespace='rent_hotel')),
    url(r'^about/$', views.about, name='about'),
    url(r'^login-or-register/$', views.login_or_register, name='login_or_register'),
    url(r'^offers/', include('offer.urls', namespace='offer')),
    url(r'^category/', include('category.urls', namespace='category')),
    url(r'^related-links/', include('related_links.urls', namespace='related_links')),
    url(r'^booking/', include('booking.urls', namespace='booking')),
    url(r'^search/$', views.search, name='search'),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/news/urls.py
from django.conf.urls import url
from . import views

urlpatterns = (

    url(r'^$', views.news_list, name='list'),
    url(r'^create/$', views.news_create, name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.news_detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.news_update, name='edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.news_delete, name='delete'),
    # url(r'^(?P<slug>[\w-]+)/$', views.news_category, name='cat'),

)

src/rent_hotel/urls.py
from django.conf.urls import url
from . import views

urlpatterns = (

    url(r'^$', views.rent_hotel_list, name='list'),
    # url(r'^create/$', views.rent_car_create, name='create'),
    # url(r'^(?P<pk>[0-9]+)/$', views.rent_car_detail, name='detail'),
    # url(r'^(?P<pk>[0-9]+)/edit/$', views.rent_car_update, name='edit'),
    # url(r'^(?P<pk>[0-9]+)/delete/$', views.rent_car_delete, name='delete'),
    # # url(r'^(?P<slug>[\w-]+)/$', views.rent_car_category, name='cat'),

)

src/news/models.py
import datetime
from django.db import models
from tours.models import Category, Tour
from easy_thumbnails.fields import ThumbnailerImageField
from django.utils.translation import ugettext as _
from django.core.urlresolvers import reverse


class Article(models.Model):
    title_PT = models.CharField(_('Title PT'), max_length=100, blank=True, null=False)
    title_EN = models.CharField(_('Title EN'), max_length=100, blank=True, null=False)
    title_DE = models.CharField(_('Title DE'), max_length=100, blank=True, null=False)
    description_PT = models.TextField(_('Description PT'), max_length=5000, blank=True, null=False)
    description_EN = models.TextField(_('Description EN'), max_length=5000, blank=True, null=False)
    description_DE = models.TextField(_('Description DE'), max_length=5000, blank=True, null=False)
    category = models.ForeignKey(Category, default=None, blank=True, null=True)
    tour = models.ForeignKey(Tour, default=None, blank=True, null=True)
    link = models.URLField(max_length=100, blank=True, null=False)
    img = ThumbnailerImageField(_('Article thumbnail'), null=True, blank=True)
    keywords_SEO = models.TextField(_('Article keywords for SEO'), max_length=5000, blank=True, null=False)
    description_SEO = models.TextField(_('Article description for SEO'), max_length=5000, blank=True, null=False)
    created_on = models.DateTimeField(default=datetime.datetime.now(), blank=True)

    def get_absolute_url(self):
        return reverse('news:detail', args=[str(self.id)])

    def get_edit_url(self):
        return reverse('news:edit', args=[str(self.id)])

    def get_delete_url(self):
        return reverse('news:delete', args=[str(self.id)])

    def __str__(self):
        return self.title_EN

    def __unicode__(self):
        return self.title_EN

    class Meta:
        ordering = ['-created_on']

src/rent_hotel/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _
from easy_thumbnails.fields import *
from autoslug.fields import *


class HotelCategory(models.Model):
    category = models.CharField(max_length=100, blank=True, null=False)
    slug = AutoSlugField(populate_from='category', unique=True, max_length=255)

    def get_absolute_url(self):
        return reverse('rent_hotel:detail', args=[str(self.slug)])

    def __str__(self):
        return self.category

    def __unicode__(self):
        return self.category


class Hotel(models.Model):
    title_PT = models.CharField(_('Title PT'), max_length=100, blank=True, null=False)
    title_EN = models.CharField(_('Title EN'), max_length=100, blank=True, null=False)
    title_DE = models.CharField(_('Title DE'), max_length=100, blank=True, null=False)
    description_PT = models.TextField(_('Hotel description PT'), max_length=1000, blank=True, null=False)
    description_EN = models.TextField(_('Hotel description EN'), max_length=1000, blank=True, null=False)
    description_DE = models.TextField(_('Hotel description DE'), max_length=1000, blank=True, null=False)
    address = models.TextField(_('Hotel address'), max_length=1000, blank=True, null=False)
    category = models.ForeignKey(HotelCategory, default=1, blank=True, null=True)
    price = models.CharField(_('Hotel price per day'), max_length=100, blank=True, null=False)
    trip_advisor_PT = models.TextField(_('Input script for widget from TripAdvisor PT'), max_length=2000, blank=True,
                                       null=False)
    trip_advisor_EN = models.TextField(_('Input script for widget from TripAdvisor EN'), max_length=2000, blank=True,
                                       null=False)
    trip_advisor_DE = models.TextField(_('Input script for widget from TripAdvisor DE'), max_length=2000, blank=True,
                                       null=False)
    # tour = models.ForeignKey(Tour, default=1, blank=True, null=True)
    # link = models.URLField(max_length=100, blank=True, null=False)
    img = ThumbnailerImageField(_('Hotel thumbnail'), null=True, blank=True)
    keywords_SEO = models.TextField(_('Hotel keywords for SEO'), max_length=1000, blank=True, null=False)
    description_SEO = models.TextField(_('Hotel description for SEO'), max_length=1000, blank=True, null=False)

    class Meta:
        # ordering = ['position', '-created_on']
        verbose_name_plural = _('Hotel')

    def get_absolute_url(self):
        return reverse('rent_hotel:detail', args=[str(self.id)])

    def get_edit_url(self):
        return reverse('rent_hotel:edit', args=[str(self.id)])

    def get_delete_url(self):
        return reverse('rent_hotel:delete', args=[str(self.id)])

    def __str__(self):
        return '%s at %s' % (self.title_EN, self.address)

    def __unicode__(self):
        return '%s at %s' % (self.title_EN, self.address)

src/tours/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from lisbon.forms import contains_html_tags, contains_url
from .models import Tour


class TourForm(forms.ModelForm):
    class Meta:
        model = Tour
        fields = [

            'category',
            'position',
            'title_PT',
            'title_EN',
            'title_DE',
            'description_PT',
            'description_EN',
            'description_DE',
            'short_description_PT',
            'short_description_EN',
            'short_description_DE',
            'price',
            'img',
            'url',
            'keywords_SEO',
            'description_SEO',

        ]


class BookNow(forms.Form):
    fullname = forms.CharField(label=_('Name'), required=True, validators=[contains_html_tags, contains_url])
    email = forms.EmailField(label=_('Email'), required=True, validators=[contains_html_tags, contains_url])
    phone = forms.CharField(label=_('Phone'), required=True, validators=[contains_html_tags, contains_url])
    message = forms.CharField(label=_('Message'), widget=forms.Textarea(), required=True,
                              validators=[contains_html_tags, contains_url])
    date = forms.DateField(label=_('From Date'), required=True)


class ContactMe(forms.Form):
    fullname = forms.CharField(label=_('Name'), required=True, validators=[contains_html_tags, contains_url])
    email = forms.EmailField(label=_('Email'), required=True, validators=[contains_html_tags, contains_url])
    phone = forms.CharField(label=_('Phone'), required=True, validators=[contains_html_tags, contains_url])
    message = forms.CharField(label=_('Message'), widget=forms.Textarea(), required=True,
                              validators=[contains_html_tags, contains_url])

src/rent_hotel/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.utils.translation import ugettext_lazy as _

from helpers.models import Helpers
from offer.models import OfferCategory
from tours.models import Category
from .models import Hotel


def get_lang(request):
    lang = request.LANGUAGE_CODE
    return lang


def get_company():
    return Helpers.objects.get(id=1).company_name


def rent_hotel_list(request):
    query = request.GET.get('q')
    if query:
        return redirect(reverse('search') + '?q=' + query)
    breadcrumbs = [
        {'url': '/', 'name': _('Home')},
        {'url': '#', 'name': _('Hotels in Lisbon'), 'active': True}
    ]
    footer = {
        'pt': Helpers.objects.get(id=1).about_footer_PT,
        'en': Helpers.objects.get(id=1).about_footer_EN,
        'de': Helpers.objects.get(id=1).about_footer_DE
    }
    queryset_list = Hotel.objects.all()
    lang = get_lang(request)
    paginator = Paginator(queryset_list, 6)
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    context = {
        'footer': {
            'about': footer[lang],
            'icon': Helpers.objects.get(id=1).footer_icon
        },
        'nav': {
            'tour_categories_list': Category.objects.all(),
            'offer_categories_list': OfferCategory.objects.all(),
        },
        'company': get_company(),
        'title': _('Hotels in Lisbon'),
        'object_list': queryset,
        'breadcrumbs': breadcrumbs,
        'page_request_var': page_request_var,
        'value': _('Add'),
    }

    return render(request, 'partials/rent-hotel.html', context)

src/templates/templates/_alerts.html
{% block messages %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <span>{{ message|safe }}</span>
</div>
{% endfor %}
{% endif %}
{% endblock %}

src/templates/templates/_car_category.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% block content %}
{% include 'templates/_breadcrumbs.html' %}
    <section>
        <div class="container">
            <div class="card-columns">
                {% for object in object_list %}
                    {% include 'templates/_offer_card.html' %}
                {% endfor %}
            </div>
            {% if user.is_staff or user.is_superuser %}
                <a class="btn btn-warning" href="{% url 'car:create' %}">
                    <i class="fa fa-plus"></i> {% trans 'Create Car' %}</a>
            {% endif %}
            {% include 'templates/_pagination.html' %}
        </div>
    </section>
{% endblock %}

src/templates/templates/_contact_details.html
{% extends 'base.html' %}
{% load i18n %}
{% block description %}{{ object.description_SEO }}{% endblock description %}
{% block keywords %}{{ object.keywords_SEO }}{% endblock keywords %}
{% block content %}
    {% load staticfiles %}
    {% include 'templates/_breadcrumbs.html' %}
    <section class="details">
        <div class="container">
            <h4 class="display-4">{{ title }}</h4>
            <div class="row">
                <div class="col-md-6">
                    {% if object.img %}
                        <img style="max-height: 500px;   object-fit: cover;" class="img-fluid" src="{% static '/media/' %}{{ object.img }}" alt="" width="100%">
                    {% else %}
                        <p style="text-align: center"><small><em>{% trans 'place for image' %}</em></small></p>
                    {% endif %}
                    <small><em>SHORT BIO:</em></small>
                    <p class="card-text text-justify"> {{ object.short_bio}}</p>
                </div>
                <div class="col-md-6">
                <small><em>CATEGORY:</em></small>
                <p class="card-text"> {{ object.category}}</p>

                <small><em>CALL ME:</em></small>
            {% if object.mobile  %}
                <p class="card-text"><span class="fa fa-mobile"></span> {{ object.mobile }}</p>
            {% endif %}


            {% if object.email  %}
                <p class="card-text"><span class="fa fa-mail-forward"></span> {{ object.email }}</p>
            {% endif %}


            {% if object.whatsapp  %}
                <p class="card-text"><span class="fa fa-whatsapp"></span> {{ object.whatsapp }}</p>
            {% endif %}


            {% if object.viber  %}
                <p class="card-text"><span>viber:</span> {{ object.viber }}</p>
            {% endif %}


            {% if object.telegram  %}
                <p class="card-text"><span>telegram: </span>{{ object.telegram }}</p>
            {% endif %}


            {% if object.skype  %}
                <p class="card-text"><span class="fa fa-skype"></span> {{ object.skype }}</p>
            {% endif %}

                <small><em>SOCIAL NETWORKS:</em></small>


            {% if object.facebook  %}
                <p><a class="card-link" href="{{ object.facebook }}">{% trans 'Follow on ' %} Facebook <span class="fa fa-facebook"></span></a></p>
            {% endif %}


            {% if object.twitter  %}
                <p><a class="card-link" href="{{ object.twitter }}">{% trans 'Follow on ' %} Twitter <span class="fa fa-twitter"></span></a></p>
            {% endif %}


            {% if object.pinterest  %}
                <p><a class="card-link" href="{{ object.pinterest }}">{% trans 'Follow on ' %} Pinterest <span class="fa fa-pinterest"></span></a></p>
            {% endif %}


            {% if object.instagram  %}
                <p><a class="card-link" href="{{ object.instagram }}">{% trans 'Follow on ' %} Instagram <span class="fa fa-instagram"></span></a></p>
            {% endif %}


            {% if object.google  %}
                <p><a class="card-link" href="{{ object.google }}">{% trans 'Follow on ' %} Google + <span class="fa fa-google-plus"></span></a></p>
        {% endif %}
            {% if user.is_staff or user.is_superuser %}
                <a class="btn btn-sm btn-danger-outline" href="{{ object.get_delete_url }}">
                    <i class="fa fa-trash"></i> {% trans 'Delete' %}</a>
                <a class="btn btn-sm btn-danger-outline" href="{{ object.get_edit_url }}">
                    <i class="fa fa-pencil-square-o"></i> {% trans 'Edit' %}</a>
            {% endif %}
                    {% include 'templates/_share.html' %}

                </div>
            </div>
        </div>
    </section>
{% endblock %}

src/templates/templates/_contact_us_form.html
{% load i18n %}
<form data-test="contact-form" name="contactForm" method="POST" action="/booking/contacts"
      enctype='multipart/form-data'>{% csrf_token %}
    <p><label for="id_fullname">Name:</label> <input id="id_fullname" data-test="contact-form__name" ng-model="fullname" name="fullname" type="text" required/></p>
    <div ng-messages="contactForm.fullname.$error" ng-show="contactForm.fullname.$touched" style="color:maroon" role="alert">
        <div ng-message="required">This field is required</div>
    </div>
    <p><label for="id_email">Email:</label> <input id="id_email" data-test="contact-form__email" ng-model="email" name="email" type="email" required/></p>
    <div ng-messages="contactForm.email.$error" ng-show="contactForm.email.$touched" style="color:maroon" role="alert">
        <div ng-message="required">This field is required</div>
    </div>
    <p><label for="id_phone">Phone:</label> <input id="id_phone" data-test="contact-form__phone" ng-model="phone" name="phone" type="text" required/></p>
    <div ng-messages="contactForm.phone.$error" ng-show="contactForm.phone.$touched" style="color:maroon" role="alert">
        <div ng-message="required">This field is required</div>
    </div>
    <p><label for="id_message">Message:</label> <textarea cols="40" data-test="contact-form__message" id="id_message" ng-model="message" name="message" rows="10" required></textarea></p>
    <div ng-messages="contactForm.message.$error" ng-show="contactForm.message.$touched" style="color:maroon" role="alert">
        <div ng-message="required">This field is required</div>
    </div>
    <input type='submit'
           class='btn btn-lg btn-primary'
           value='{% trans 'Send' %}'
           data-test="contact-form__submit-button"
           ng-disabled="contactForm.$invalid || wrongCaptchaResponse"/>
    <div class="g-recaptcha" data-sitekey="6LfDoCMUAAAAAAomUjyHcUDKcFj833NuvBNlX2D3" data-callback="recaptchaResponse"></div>
</form>

src/templates/templates/_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <nav>
        {% include 'templates/_breadcrumbs.html' %}
    </nav>
    <section>
        <div class="container">
            <h4 class="display-4">{{ title }}</h4>
            <form method="POST" action="{{ request.get_full_path }}" enctype="multipart/form-data">{% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-lg btn-primary" value="{{ value }}" />
            </form>
        </div>
    </section>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=37uyjtklf856zryk0rp6gpo3t6a4a4skongxa1vs6r5no7vv"></script>
    <script>
        _.map(['textarea', 'input', 'label', 'select'], function(el){
                    el === 'label' && $(el).attr('type') !== 'submit'
                            ? $(el).addClass('my-label')
                            : $(el).addClass('form-control');
                });
            $('select').css('height', '40px');

            const datePicker = $('#id_created_on');
            if (datePicker !== null || datePicker !== undefined) {
                datePicker.datepicker();
            }
    </script>

    <script>
    _.map([
        '#id_description_PT',
        '#id_description_EN',
        '#id_description_DE',
        '#id_short_description_PT',
        '#id_short_description_EN',
        '#id_short_description_DE'], function(element) {
        tinymce.init({ selector: element })
    })
    </script>
{% endblock %}

src/templates/templates/_languages_footer.html
{% load i18n %}
{% for lang in LANGUAGES %}
    <form id="setLang_{{ lang.1}}_footer"
          action="/i18n/setlang/"
          method="POST"
          class="col-xs-12 col-sm-4 col-md-4">
        {% csrf_token %}
        <input name="next" type="hidden" value="{{ request.path }}">
        <input type="hidden" name="language" value="{{ lang.0 }}">
        <a href="#" onclick="$('#setLang_{{ lang.1 }}_footer').submit();
                return false;"><i class="flag-icon flag-icon-{% if lang.0 == 'en' %}gb{% else %}{{ lang.0 }}{% endif %}"></i>  <span>{{ lang.1 }}</span></a>
    </form>
{% endfor %}

src/templates/templates/_news_card.html
{% load thumbnail %}
{% load i18n %}
{% load get_translated_title %}
{% load get_translated_description %}

<div class="card">

  {% if object.img %}
    <a href="{{ object.id }}">
      <img style="height: 350px;width: 100%; object-fit: cover;" class="img-fluid"
           src="{% thumbnail object.img 720x480 crop="smart" %}" alt="{{ object.title_EN }}" width="100%">
    </a>
  {% else %}
    <p style="text-align: center">
      <small><em>{% trans 'place for image' %}</em></small>
    </p>
  {% endif %}

  <div class="card-block">

    <h2>{% get_translated_title object request.LANGUAGE_CODE %}</h2>
    <p class="text-justify">
      {% autoescape off %}
        {% get_translated_description object request.LANGUAGE_CODE %}
      {% endautoescape %}
    </p>

    {% if object.category %}
      <p>
        <small>
          <em class="text-uppercase">{% trans 'category' %}: </em>
          <em>
            <a href="{{ object.category.get_absolute_url }}">{{ object.category }}</a>
          </em>
        </small>
      </p>
    {% endif %}

    {% if object.tour %}
      <p>
        <small>
          <em class="text-uppercase">{% trans 'tour' %}: </em>
          <em>
            <a href="{{ object.tour.get_absolute_url }}">{{ object.tour }}</a>
          </em>
        </small>
      </p>
    {% endif %}

    {% include 'templates/_share.html' %}
    {% include 'templates/_CRUD.html' %}
  </div>
</div>

src/templates/templates/_news_details.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}
{% load thumbnail %}
{% block description %}{{ object.description_SEO }}{% endblock description %}
{% block keywords %}{{ object.keywords_SEO }}{% endblock keywords %}
{% block content %}
    {% include 'templates/_breadcrumbs.html' %}
    <section class="details">
        <div class="container">
            <h1 class="display-4">{{ title }}</h1>
            <div class="row">
                <div class="row">
                <div class="col-md-6">
                    <div class="card-block">
                        {% if object.img %}
                            <img style="max-height: 500px;   object-fit: cover;" class="img-fluid" src="{% thumbnail object.img 720x480 crop="smart" %}" alt="" width="100%">
                        {% else %}
                            <p style="text-align: center"><small><em>{% trans 'place for image' %}</em></small></p>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-6">
                    <h4 class="card-title">{{ object.title|upper }}</h4>
                    <p class="card-text text-justify">{{ object.description|safe }}</p>
                    {% include 'templates/_share.html' %}
                    {% if user.is_staff or user.is_superuser %}
                        <a class="btn btn-sm btn-danger-outline" href="{% url 'news:list' %}{{ object.id }}/delete/">
                            <i class="fa fa-trash"></i> {% trans 'Delete' %}</a>
                        <a class="btn btn-sm btn-danger-outline" href="{% url 'news:list' %}{{ object.id }}/edit/">
                            <i class="fa fa-pencil-square-o"></i> {% trans 'Edit' %}</a>
                    {% endif %}
                </div>
                </div>
            </div>
            {% if user.is_staff or user.is_superuser %}
                <a class="btn btn-warning" href="{% url 'tour:create' %}">
                    <i class="fa fa-plus"></i> {% trans 'Create News' %}</a>
            {% endif %}
        </div>
    </section>
{% endblock %}

src/templates/templates/_rent_hotel.html
{% load thumbnail %}
{% load i18n %}
<div class="refills-card">
    <div class="refills-card-image">
        <img src="{% thumbnail object.img 720x480 crop="smart" %}" alt="{{ object.title_EN }}">
    </div>
    <div class="refills-card-header">
        {% if 'pt' in request.LANGUAGE_CODE %}
            {{ object.title_PT }}{% if object.price %} | {{ object.price }} € {% endif %}
        {% elif 'en' in request.LANGUAGE_CODE %}
            {{ object.title_EN }}{% if object.price %} | {{ object.price }} € {% endif %}
        {% elif 'de' in request.LANGUAGE_CODE %}
            {{ object.title_DE }}{% if object.price %} | {{ object.price }} € {% endif %}
        {% endif %}
    </div>
    <div class="refills-card-copy">
        {% if 'pt' in request.LANGUAGE_CODE %}
            <div class="row">
                <div class="col-md-6">
                    {{ object.trip_advisor_PT | safe }}
                </div>
                <div class="col-md-6">
                    {% include 'templates/buttons/_booking.com.html' %}
                </div>
            </div>
            <p><small class="text-muted text-uppercase">{% trans 'description'%}: </small>{{ object.description_PT }}</p>
            {% elif 'en' in request.LANGUAGE_CODE %}
                <div class="row">
                    <div class="col-md-6">
                        {{ object.trip_advisor_EN | safe }}
                    </div>
                    <div class="col-md-6">
                        {% include 'templates/buttons/_booking.com.html' %}
                    </div>
                </div>
                <p><small class="text-muted text-uppercase">{% trans 'description'%}: </small>{{ object.description_EN }}</p>
                    {% elif 'de' in request.LANGUAGE_CODE %}
                        <div class="row">
                            <div class="col-md-6">
                                {{ object.trip_advisor_DE | safe }}
                            </div>
                            <div class="col-md-6">
                                {% include 'templates/buttons/_booking.com.html' %}
                            </div>
                        </div>
                        <p><small class="text-muted text-uppercase">{% trans 'description'%}: </small>{{ object.description_DE }}</p>
        {% endif %}
        <p><small class="text-muted text-uppercase">{% trans 'address'%}: </small>{{ object.address }}</p>
        <p><small class="text-muted text-uppercase">{% trans 'category'%}: </small>{{ object.category }}</p>
    </div>
</div>

src/templates/templates/_tour_card_de.html
{% load thumbnail %}
{% load i18n %}
<div class="card">
{% load i18n %}
    {% if object.img %}
        <a href="{{ object.get_absolute_url }}">
            <img style="height: 350px;width: 100%; object-fit: cover;" class="img-fluid" src="{% thumbnail object.img 720x480 crop="smart" %}" alt="{{ object.title_DE }}">
        </a>
    {% else %}
        {% if object.url  %}
            <a href="{{ object.get_absolute_url }}">
                <img style="height: 350px;width: 100%;   object-fit: cover;" class="img-fluid" src="{{ object.url }}" alt="{{ object.title_DE }}">
            </a>
        {% else %}
            <p style="text-align: center"><small><em>{% trans 'place for image' %}</em></small></p>
        {% endif %}
    {% endif %}
    <div class="card-block">
        <h4 class="card-title">{{ object.title_DE|upper }}
            {% if object.price %}
                | {{ object.price }} €
            {% endif %}</h4>
        <p class="card-text text-justify">{{ object.short_description_DE|safe}}</p>
        <p>{{ object.created_on }}</p>
        <p><small><em class="text-uppercase">{% trans 'category' %}: </em><em><a href="{{ object.category.get_absolute_url }}">{{ object.category }}</a></em></small></p>
        <a href="{{ object.id }}" class="btn btn-danger text-uppercase" data-toggle="modal" data-target="#bookingFormModal" data-test="booking-form-modal-trigger" data-whatever="@getbootstrap">{% trans 'book now' %}</a>
        {% include 'templates/buttons/_details.html' %}
    </div>
    <div class="card-footer">
        {% include 'templates/_share.html' %}
        {% if user.is_staff %}
             <a class="btn btn-sm btn-danger-outline" href="{{ object.get_edit_url }}">
                    <i class="fa fa-pencil-square-o"></i> {% trans 'Edit' %}</a>
            <a type="button" class="btn btn-sm btn-danger-outline" onclick="delete_contact({{ object.id }})" data-toggle="modal" data-target=".delete_tour"><i class="fa fa-trash"></i> {% trans 'Delete'%}</a></a>
        {% endif %}
    </div>
</div>